# Generated by Django 4.2.7 on 2023-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='esPrivado',
            field=models.BooleanField(default=False),
        ),
    ]
