# Generated by Django 4.2.7 on 2023-12-22 02:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0004_proyecto_imagen_delete_imagenesproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenesProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sitio.proyecto')),
            ],
        ),
    ]
