# Generated by Django 4.2.7 on 2023-12-22 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0005_remove_proyecto_imagen_imagenesproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproyecto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
