# Generated by Django 4.2.7 on 2023-12-22 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0007_alter_imagenesproyecto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproyecto',
            name='imagen',
            field=models.ImageField(default='imagen', upload_to='imagenes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
