# Generated by Django 5.0 on 2023-12-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0008_alter_imagenesproyecto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
