# Generated by Django 5.0 on 2024-01-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0009_proyecto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
