# Generated by Django 5.0 on 2024-01-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0011_proyecto_baños_proyecto_habitaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='correo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
