# Generated by Django 4.2.7 on 2024-02-09 03:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0012_estudio_correo_estudio_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesproyecto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
