# Generated by Django 4.2.7 on 2024-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0014_alter_arquitecto_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquitecto',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
